apiVersion: v1
kind: Namespace
metadata:
  name: springboot
  labels:
    name: springboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: springboot
spec:
  selector:
    matchLabels:
      app: javaapp
  replicas: 1
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: javaapp
        imagePullPolicy: Always
        image: georgelouis01/javaapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javaapp
  namespace: springboot
spec:
  type: NodePort
  selector:
    app: javaapp
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007 # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)